#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

# Source shared files
source "${SCRIPT_DIR}/.environment"
source "${SCRIPT_DIR}/.functions"

# Log start
console_log "$0: Starting..."

# Cleaning up old snapshots
console_log "Delete old snapshots..."
find ${ARCH_UPDATE_SNAPSHOT_DIR} -mtime +${ARCH_UPDATE_SNAPSHOT_KEEP_DAYS} -delete

# Create snapshot LV
console_log "Creating LVM snapshot..."
sudo lvcreate --snapshot -L 2GB -n ${ARCH_UPDATE_ROOT_LV}-snap /dev/${ARCH_UPDATE_VG}/${ARCH_UPDATE_ROOT_LV} || (console_log "ERROR - Re-run after cleanup: sudo lvremove $ARCH_UPDATE_VG/${ARCH_UPDATE_ROOT_LV}-snap" && exit 1)

# Create snapshot file
console_log "Exporting snapshot to file..."
sudo dd if=/dev/${ARCH_UPDATE_VG}/${ARCH_UPDATE_ROOT_LV}-snap bs=100M | gzip -c -9 > ${ARCH_UPDATE_SNAPSHOT_DIR}/${ARCH_UPDATE_ROOT_LV}-snap-$(date +"%F").gz

# Remove snapshot LV
console_log "Deleting LVM snapshot.."
sudo lvremove -y ${ARCH_UPDATE_VG}/${ARCH_UPDATE_ROOT_LV}-snap

# Run the update
console_log "Pacman update..."
yes | sudo pacman -Syu

# Go through AUR dirs
console_log "AUR upgrade..."
for this_aur in ${ARCH_UPDATE_AUR_DIR}/*
do
  cd ${this_aur}
  git pull > /dev/null
  yes | makepkg -fsi
done

# Log finish
console_log "$0: Finished."
