#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"
source "${SCRIPT_DIR}/.functions"

# Log start
console_log "$0: Starting..."

# rsnapshot
console_log "Running rsnapshot..."
sudo rsnapshot -c "${SCRIPT_DIR}/.rsnapshot.conf" upgrade

# Create snapshot file
console_log "Unmounting external FS..."
sudo umount ${ARCH_UPDATE_EXTERNAL_MNT}

# Run the update
console_log "Pacman update..."
yay -Syu

# Log finish
console_log "$0: Finished."
