#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"
source "${SCRIPT_DIR}/.functions"

# Log start
console_log "$0: Starting..."

# Perform rclone
eval rclone sync --drive-auth-owner-only ${GDRIVE_EXTRA_PARAMS} ${GDRIVE_BACKUP_SOURCE} ${GDRIVE_BACKUP_TARGET}

# Log finish
console_log "$0: Finished."
