#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"
source "${SCRIPT_DIR}/.functions"

# Log start
console_log "$0: Starting..."

# Perform get
getmail

# Log finish
console_log "$0: Finished."
