#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"
source "${SCRIPT_DIR}/.functions"

# Log start
console_log "$0: Starting..."

# Perform rsync
eval rsync -avh --delete --delete-excluded --exclude-from "${RSYNC_EXCLUDE_FROM}" "${RSYNC_BACKUP_SOURCE}/" "${RSYNC_BACKUP_TARGET}"

# Log finish
console_log "$0: Finished."
