#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"

# Check if any unattached session
UNATTACHED_SESSION="$(tmux list-session | egrep "\(group ${TMUX_SESSION_GROUP}\)$" | head -n 1 | cut -d':' -f1)"

# If we found an unattached session, attach to it
if [ -n "$UNATTACHED_SESSION" ]
then
  tmux attach-session -t $UNATTACHED_SESSION

# Otherwise, create a new session in the group
else
  tmux new-session -t $TMUX_SESSION_GROUP
fi
