#!/usr/bin/env bash

# Break on error
set -e

# Get import dir
SCRIPT_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# Source shared files
source "${SCRIPT_DIR}/.environment"

# Check if any unattached session
tmux new-session -t $TMUX_SESSION_GROUP\; choose-tree
